CREATE TABLE IF NOT EXISTS responsible_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    phone_number VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    barbershop_id BIGINT NOT NULL
);

ALTER TABLE clients ADD COLUMN IF NOT EXISTS responsible_contact_id BIGINT;

INSERT INTO responsible_contacts (full_name, phone_number, email, barbershop_id)
SELECT
    NULLIF(TRIM(CONCAT(COALESCE(c.first_name, ''), ' ', COALESCE(c.last_name, ''))), ''),
    c.phone_number,
    c.email,
    c.barbershop_id
FROM clients c
WHERE c.phone_number IS NOT NULL
  AND c.barbershop_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM responsible_contacts rc
      WHERE rc.phone_number = c.phone_number
        AND rc.barbershop_id = c.barbershop_id
  );

UPDATE clients
SET responsible_contact_id = (
    SELECT MIN(rc.id)
    FROM responsible_contacts rc
    WHERE rc.phone_number = clients.phone_number
      AND rc.barbershop_id = clients.barbershop_id
)
WHERE responsible_contact_id IS NULL
  AND phone_number IS NOT NULL
  AND barbershop_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_responsible_contacts_barbershop_id
    ON responsible_contacts (barbershop_id);

CREATE INDEX IF NOT EXISTS idx_responsible_contacts_phone_barbershop
    ON responsible_contacts (phone_number, barbershop_id);

CREATE INDEX IF NOT EXISTS idx_clients_responsible_contact_id
    ON clients (responsible_contact_id);
