CREATE TABLE visit_payment_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    payment_method VARCHAR(255),
    notes VARCHAR(500)
);

CREATE INDEX idx_visit_payment_movements_visit_id ON visit_payment_movements (visit_id);
CREATE INDEX idx_visit_payment_movements_type ON visit_payment_movements (type);

INSERT INTO visit_payment_movements (visit_id, type, amount, occurred_at, payment_method, notes)
SELECT v.id, 'PAYMENT', v.total_amount, COALESCE(v.paid_at, CURRENT_TIMESTAMP), COALESCE(v.payment_method, 'CASH'), 'Pago migrado desde la visita'
FROM visits v
WHERE v.payment_status = 'PAID'
  AND v.total_amount > 0
  AND NOT EXISTS (
      SELECT 1
      FROM visit_payment_movements m
      WHERE m.visit_id = v.id
        AND m.type = 'PAYMENT'
  );

INSERT INTO visit_payment_movements (visit_id, type, amount, occurred_at, payment_method, notes)
SELECT v.id, 'PAYMENT', v.total_amount, COALESCE(v.paid_at, CURRENT_TIMESTAMP), COALESCE(v.payment_method, 'CASH'), 'Pago migrado desde la visita reembolsada'
FROM visits v
WHERE v.payment_status = 'REFUNDED'
  AND v.total_amount > 0
  AND NOT EXISTS (
      SELECT 1
      FROM visit_payment_movements m
      WHERE m.visit_id = v.id
        AND m.type = 'PAYMENT'
  );

INSERT INTO visit_payment_movements (visit_id, type, amount, occurred_at, payment_method, notes)
SELECT v.id, 'REFUND', v.total_amount, COALESCE(v.paid_at, CURRENT_TIMESTAMP), COALESCE(v.payment_method, 'CASH'), 'Reembolso migrado desde la visita'
FROM visits v
WHERE v.payment_status = 'REFUNDED'
  AND v.total_amount > 0
  AND NOT EXISTS (
      SELECT 1
      FROM visit_payment_movements m
      WHERE m.visit_id = v.id
        AND m.type = 'REFUND'
  );
