CREATE TABLE employee_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_employee_schedules_employee FOREIGN KEY (employee_id) REFERENCES users(id),
    CONSTRAINT fk_employee_schedules_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
);

CREATE INDEX idx_employee_schedules_employee_branch ON employee_schedules (employee_id, branch_id);
CREATE INDEX idx_employee_schedules_branch_day ON employee_schedules (branch_id, day_of_week);
