CREATE TABLE schedule_weekly_defaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(16) NOT NULL,
    slots VARCHAR(1000) NOT NULL,
    owner_id BIGINT,
    branch_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX idx_schedule_weekly_defaults_branch_day
    ON schedule_weekly_defaults (branch_id, day_of_week);

INSERT INTO schedule_weekly_defaults (day_of_week, slots, owner_id, branch_id)
SELECT days.day_of_week, COALESCE(NULLIF(settings.default_schedule_slots, ''), '10:00,10:30,11:00,11:30,12:00,12:30,13:00,13:30,14:00,14:30,15:00,15:30,16:00,16:30,17:00,17:30,18:00,18:30,19:00,19:30,20:00'), settings.owner_id, settings.branch_id
FROM app_settings settings
JOIN (
    SELECT 'MONDAY' AS day_of_week
    UNION ALL SELECT 'TUESDAY'
    UNION ALL SELECT 'WEDNESDAY'
    UNION ALL SELECT 'THURSDAY'
    UNION ALL SELECT 'FRIDAY'
    UNION ALL SELECT 'SATURDAY'
    UNION ALL SELECT 'SUNDAY'
) days ON 1 = 1
WHERE settings.branch_id IS NOT NULL
  AND settings.id = (
      SELECT MIN(base_settings.id)
      FROM app_settings base_settings
      WHERE base_settings.branch_id = settings.branch_id
  );
